### ISSUE TITLE
setup-hangs-fails-at-final-step-3

### ISSUE THREAD

**Issue by dkebler** [photo/frontend#1572]
Having the same problem as this person
http://superuser.com/questions/777811/trovebox-openphoto-setup-hangs-fails-at-final-step-3

Followed all the advice.  Yours, the "good" answer.

Used your 3 minute script on ubuntu 14.04 with latest Apache and Php5.
Phpinfo confirms mcrypt loaded.
all good with databse,  recreated it and user to be sure. 
(have serveral other mysql/php based installs including recent wordpress)

Where is there a config file I can just edit instead of trying to get this to work?

below is the source of "blank" setup/3 as it was returned. 

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">
    
    <link href="//fonts.googleapis.com/css?family=Lato:300,400,700,300italic,400italic,700italic&.css" rel="stylesheet">
          <link href="/assets/versioned/fe/themes/fabrizio1.0/stylesheets/lessc?f=less/index.less" rel="stylesheet">
        
    <link rel="shortcut icon" href="/assets/themes/fabrizio1.0/images/favicon.ico">
    <link rel="apple-touch-icon" href="/assets/themes/fabrizio1.0/images/apple-touch-icon.png">
    <link rel="apple-touch-icon" sizes="72x72" href="/assets/themes/fabrizio1.0/images/apple-touch-icon-72x72.png">
    <link rel="apple-touch-icon" sizes="114x114" href="/assets/themes/fabrizio1.0/images/apple-touch-icon-114x114.png">

**Comment by dkebler** [comment]
All other than the three directories set in the script are set root:root.   Is that ok?
Deleted openphoto folder and reran the script without --quiet.  All seems good.  Issue persists.

**Comment by nakedgun** [comment]
Most failures on this page are due to missing extensions (e.g. mcrypt, oauth) or failure to connect to MySQL. If localhost doesn't work, try 127.0.0.1. Ensure the DB is empty. If you're running MySQL on a non-standard port (e.g. not 3306), add this to the setup page.

Depending on your config, check _php_error.log_  for any exceptions caught via EPI. This will include enough information to troubleshoot the cause of failure.

**Comment by dkebler** [comment]
>(e.g. mcrypt, oauth)
both loaded confirmed by phpinfo and looking in php5 directory

>or failure to connect to MySQL. If localhost doesn't work, try 127.0.0.1.
tried both, I use localhost in all my other php/msql installs and that
works.

>Ensure the DB is empty.
checked.

running on standard port
>If you're running MySQL on a non-standard port (e.g. not 3306), add this
to the setup page.

>Depending on your config, check *php_error.log* for any exceptions caught
> via EPI. This will include enough information to troubleshoot the cause of
> failure.
>
errors below but above this is the errors I already shared which indicate
that that the **database values are not getting lifted from the form on
page two** and or not getting written before getting used to create the
database tables. This is confirmed by these errors where FROM in sql has no
value.   Am I having a write permission problem?  I checked userdata and
userdata/config folder has owner:group www-data:www-data

This is becoming a time suck.  Can I just do this manually?  I see a
template.ini in configs folder.  If I fill that out to what name/where do I
save it (userdata/config?) ?   How do I run the sql statement to generate
the tables? then how to to turn off the setup pages from loading?

As I mentioned I have several other apache/php/mysql web app installs on
this server with no write/install issues including wordpress.

```
*Notice*: curl_setopt(): CURLOPT_SSL_VERIFYHOST no longer accepts the value
1, value 2 will be used instead in
*/var/www/openphoto/src/libraries/external/aws/lib/requestcore/requestcore.class.php*
on line *613*

*Notice*: curl_setopt(): CURLOPT_SSL_VERIFYHOST no longer accepts the value
1, value 2 will be used instead in
*/var/www/openphoto/src/libraries/external/aws/lib/requestcore/requestcore.class.php*
on line *613*

*Fatal error*: Uncaught exception 'EpiDatabaseQueryException' with message
'Query error: SQLSTATE[42S02]: Base table or view not found: 1146 Table
'trovebox.user' doesn't exist - SELECT * FROM `user` WHERE `id`=:owner ' in
/var/www/openphoto/src/libraries/external/epi/EpiException.php:13 Stack
trace: #0
/var/www/openphoto/src/libraries/external/epi/EpiDatabase.php(120):
EpiException::raise(Object(EpiDatabaseQueryException)) #1
/var/www/openphoto/src/libraries/external/epi/EpiDatabase.php(79):
EpiDatabase->prepare('SELECT * FROM `...', Array) #2
/var/www/openphoto/src/libraries/adapters/DatabaseMySql.php(922):
EpiDatabase->one('SELECT * FROM `...', Array) #3
/var/www/openphoto/src/libraries/models/User.php(246):
DatabaseMySql->getUser('admin@duranguit...') #4
/var/www/openphoto/src/libraries/models/User.php(159):
User->getUserByEmail('admin@duranguit...') #5
/var/www/openphoto/src/html/assets/themes/fabrizio1.0/templates/partials/titles.php(9):
User->getNameFromEmail('admin@duranguit...') #6
/var/www/openphoto/src/libraries/ in
*/var/www/openphoto/src/libraries/external/epi/EpiException.php* on line

*13```*

**Comment by nakedgun** [comment]
With your preferred MySQL tool, connect to the EC2 DB from your machine using the same credentials and database. Drop any existing tables which exist. Try creating a table to verify permissions. If all is good, setup should work. However, the manual approach, should all else fail:

> **Can I just do this manually?  I see a
template.ini in configs folder.  If I fill that out to what name/where do I
save it (userdata/config?) ?   How do I run the sql statement to generate
the tables? then how to to turn off the setup pages from loading?**

1. On local dev, do the install, SQL dump the database and backup /userdata/configs/%host%.ini . 
2. Copy this file to the EC2 instance and rename %host% to match the server's hostname. 
3. Import the SQL database and the setup process will be bypassed. 

For this to work, MySQL credentials on dev/ec2 need to match, since they're written encrypted in site.ini

**Comment by dkebler** [comment]
don't have a local lamp installed.  No SQL available to generate database?

On Sat, Mar 28, 2015 at 10:56 AM, nakedgun <notifications@github.com> wrote:

> With your preferred MySQL tool, connect to the EC2 DB from your machine
> using the same credentials and database. Drop any existing tables which
> exist. Try creating a table to verify permissions. If all is good, setup
> should work. However, the manual approach, should all else fail:
>
>
>
>
> *Can I just do this manually? I see a template.ini in configs folder. If I
> fill that out to what name/where do I save it (userdata/config?) ? How do I
> run the sql statement to generate the tables? then how to to turn off the
> setup pages from loading?*
>
>
>    1. On local dev, do the install, SQL dump the database and backup
>    /userdata/configs/%host%.ini .
>    2. Copy this file to the EC2 instance and rename %host% to match the
>    server's hostname.
>    3. Import the SQL database and the setup process will be bypassed.
>
> For this to work, MySQL credentials on dev/ec2 need to match, since
> they're written encrypted in site.ini
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/photo/frontend/issues/1572#issuecomment-87274073>.
>



-- 
Cheers, Cuidate, TTFN <http://www.youtube.com/watch?v=5Gu50vq5ux4>
David

**Comment by dkebler** [comment]
ok, did a local lamp install.  Now database tables are created but page 3
gives 500 error and no ini file written in /userdata/configs

beyond mysql and S3 entries what else needs to be filled in in the
template.ini

Honestly, not very confident that trovebox will work once I follow your
last instructions given this install is pretty much a failure.  Any
thoughts on why?  Some particular issue with Ubuntu lamp?



On Sun, Mar 29, 2015 at 7:11 AM, David Kebler <d@kebler.net> wrote:

> don't have a local lamp installed.  No SQL available to generate database?
>
> On Sat, Mar 28, 2015 at 10:56 AM, nakedgun <notifications@github.com>
> wrote:
>
>> With your preferred MySQL tool, connect to the EC2 DB from your machine
>> using the same credentials and database. Drop any existing tables which
>> exist. Try creating a table to verify permissions. If all is good, setup
>> should work. However, the manual approach, should all else fail:
>>
>>
>>
>>
>> *Can I just do this manually? I see a template.ini in configs folder. If
>> I fill that out to what name/where do I save it (userdata/config?) ? How do
>> I run the sql statement to generate the tables? then how to to turn off the
>> setup pages from loading?*
>>
>>
>>    1. On local dev, do the install, SQL dump the database and backup
>>    /userdata/configs/%host%.ini .
>>    2. Copy this file to the EC2 instance and rename %host% to match the
>>    server's hostname.
>>    3. Import the SQL database and the setup process will be bypassed.
>>
>> For this to work, MySQL credentials on dev/ec2 need to match, since
>> they're written encrypted in site.ini
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/photo/frontend/issues/1572#issuecomment-87274073>.
>>
>
>
>
> --
> Cheers, Cuidate, TTFN <http://www.youtube.com/watch?v=5Gu50vq5ux4>
> David
>



-- 
Cheers, Cuidate, TTFN <http://www.youtube.com/watch?v=5Gu50vq5ux4>
David

**Comment by jmathai** [comment]
@dkebler what's in your error log when you receive the 500?

**Comment by gr8tushar** [comment]
@dkebler hi, I am also facing the same issue. Did you find a solution to that ?

**Comment by russmac** [comment]
The setup script does not enable mycrpt.so , (fixed)

With the DB user in question having complete access. setup fails.

"127.0.0.1           | root             | *0F95AFF51C9ACE907CA57DAEB3404D97675A0117 | Y           | Y           | Y           | Y           | Y           | Y         | Y           | Y             | Y            | Y         | Y          | Y               | Y          | Y          | Y            | Y          | Y                     | Y                | Y            | Y               | Y                | Y                | Y              | Y                   | Y                  | Y                | Y "


The database setup, appears to fails due to the user table not existing. Before its actually created.

"Table 'photos.user' doesn't exist - SELECT * FROM `user` WHERE `id`=:owner '"

[Sat May 09 03:32:20.921745 2015] [:error] [pid 26625] [client 10.0.0.7:17986] PHP Fatal error:  Uncaught exception 'EpiDatabaseQueryException' with message 'Query error: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'photos.user' doesn't exist - SELECT * FROM `user` WHERE `id`=:owner ' in /var/www/openphoto/src/libraries/external/epi/EpiException.php:13\nStack trace:\n#0 /var/www/openphoto/src/libraries/external/epi/EpiDatabase.php(120): EpiException::raise(Object(EpiDatabaseQueryException))\n#1 /var/www/openphoto/src/libraries/external/epi/EpiDatabase.php(79): EpiDatabase->prepare('SELECT * FROM `...', Array)\n#2 /var/www/openphoto/src/libraries/adapters/DatabaseMySql.php(922): EpiDatabase->one('SELECT * FROM `...', Array)\n#3 /var/www/openphoto/src/libraries/models/User.php(246): DatabaseMySql->getUser('russmac@interno...')\n#4 /var/www/openphoto/src/libraries/models/User.php(159): User->getUserByEmail('private@interno...')\n#5 /var/www/openphoto/src/html/assets/themes/fabrizio1.0/templates/partials/titles.php(9): User->getNameFromEmail('russmac@interno...')\n#6 /var/www/openphoto/src/libraries/ex in /var/www/openphoto/src/libraries/external/epi/EpiException.php on line 13, referer: http://photo.private.net/setup/3

Ive been looking everywhere for some SQL to create it manually.

**Comment by russmac** [comment]
# Devops FTW.
I found the SQL that is not provided anywhere in the source, Enclosed in PHP tags and using PHP vars 
/var/www/openphoto/src/configs/upgrade/db/mysql/mysql-base.php

I stripped the PHP completely and came up with this, 

https://gist.github.com/russmac/a4498037c8300b717b56

Piping this to my DB encountered errors,

root@photoxx:/var/www# mysql photos < trovebox.sql -p
Enter password: 
ERROR 1064 (42000) at line 125: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'group (
    `id` varchar(6) NOT NULL,
    `owner` varchar(127) NOT NULL,
    `ac' at line 1

Hamburgers! So I inspected the DB and saw that the other tables WERE being generated.
This gave me an idea, to just use the users table.

mysql>   CREATE TABLE IF NOT EXISTS user (
    ->    `id` varchar(255) NOT NULL COMMENT 'User''s email address',
    ->    `password` varchar(64) NOT NULL,
    ->    `extra` text NOT NULL,
    ->    `timestamp` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    ->    PRIMARY KEY (`id`)
    ->   ) ENGINE=InnoDB DEFAULT CHARSET=utf8;
Query OK, 0 rows affected (0.01 sec)

*BAM* , I was sure it would work now .

[Sat May 09 04:25:06.775178 2015] [:error] [pid 26855] [client 10.0.0.6:19548] {severity:crit, description:"SQLSTATE[HY000] [2005] Unknown MySQL server host '127.0.0.1:3306' (0)", additional:}, referer: http://photo.private.net/setup/3
[Sat May 09 04:25:06.775529 2015] [:error] [pid 26855] [client 10.0.0.6:19548] {severity:warn, description:"Query error: SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry 'private@internode.on.net' for key 'PRIMARY' - INSERT INTO `user` (`id`,`password`,`extra`) VALUES (:id,:password,:extra)", additional:}, referer: http://photo.private.net/setup/3
[Sat May 09 04:25:07.196306 2015] [:error] [pid 26855] [client 10.0.0.6:19548] PHP Notice:  Undefined variable: mySqlHost in /var/www/openphoto/src/templates/setup.php on line 99, referer: http://photo.private.net/setup/3
[Sat May 09 04:25:07.196321 2015] [:error] [pid 26855] [client 10.0.0.6:19548] PHP Notice:  Undefined variable: mySqlUser in /var/www/openphoto/src/templates/setup.php on line 102, referer: http://photo.private.net/setup/3
[Sat May 09 04:25:07.196326 2015] [:error] [pid 26855] [client 10.0.0.6:19548] PHP Notice:  Undefined variable: mySqlPassword in /var/www/openphoto/src/templates/setup.php on line 105, referer: http://photo.private.net/setup/3
[Sat May 09 04:25:07.196330 2015] [:error] [pid 26855] [client 10.0.0.6:19548] PHP Notice:  Undefined variable: mySqlDb in /var/www/openphoto/src/templates/setup.php on line 108, referer: http://photo.private.net/setup/3
[Sat May 09 04:25:07.196334 2015] [:error] [pid 26855] [client 10.0.0.6:19548] PHP Notice:  Undefined variable: mySqlTablePrefix in /var/www/openphoto/src/templates/setup.php on line 111, referer: http://photo.private.net/setup/3
[Sat May 09 04:25:07.264825 2015] [:error] [pid 26855] [client 10.0.0.6:19548] PHP Notice:  Undefined variable: mySqlHost in /var/www/openphoto/src/templates/setup.php on line 99, referer: http://photo.private.net/setup/3
[Sat May 09 04:25:07.264837 2015] [:error] [pid 26855] [client 10.0.0.6:19548] PHP Notice:  Undefined variable: mySqlUser in /var/www/openphoto/src/templates/setup.php on line 102, referer: http://photo.private.net/setup/3
[Sat May 09 04:25:07.264842 2015] [:error] [pid 26855] [client 10.0.0.6:19548] PHP Notice:  Undefined variable: mySqlPassword in /var/www/openphoto/src/templates/setup.php on line 105, referer: http://photo.private.net/setup/3
[Sat May 09 04:25:07.264847 2015] [:error] [pid 26855] [client 10.0.0.6:19548] PHP Notice:  Undefined variable: mySqlDb in /var/www/openphoto/src/templates/setup.php on line 108, referer: http://photo.private.net/setup/3
[Sat May 09 04:25:07.264851 2015] [:error] [pid 26855] [client 10.0.0.6:19548] PHP Notice:  Undefined variable: mySqlTablePrefix in /var/www/openphoto/src/templates/setup.php on line 111, referer: http://photo.private.net/setup/3
[Sat May 09 04:25:07.333280 2015] [:error] [pid 26855] [client 10.0.0.6:19548] PHP Notice:  Undefined variable: mySqlHost in /var/www/openphoto/src/templates/setup.php on line 99, referer: http://photo.private.net/setup/3
[Sat May 09 04:25:07.333291 2015] [:error] [pid 26855] [client 10.0.0.6:19548] PHP Notice:  Undefined variable: mySqlUser in /var/www/openphoto/src/templates/setup.php on line 102, referer: http://photo.private.net/setup/3
[Sat May 09 04:25:07.333296 2015] [:error] [pid 26855] [client 10.0.0.6:19548] PHP Notice:  Undefined variable: mySqlPassword in /var/www/openphoto/src/templates/setup.php on line 105, referer: http://photo.private.net/setup/3
[Sat May 09 04:25:07.333300 2015] [:error] [pid 26855] [client 10.0.0.6:19548] PHP Notice:  Undefined variable: mySqlDb in /var/www/openphoto/src/templates/setup.php on line 108, referer: http://photo.private.net/setup/3
[Sat May 09 04:25:07.333304 2015] [:error] [pid 26855] [client 10.0.0.6:19548] PHP Notice:  Undefined variable: mySqlTablePrefix in /var/www/openphoto/src/templates/setup.php on line 111, referer: http://photo.private.net/setup/3

It didnt, Hamburgers. However it DID produce a shitload of different errors.

So I did the devops things and tried something completely different, I tried entering a non existent DB from the same browser session, Considernig different erros from the last attempt would have parsed more code and therefor the actions would have a slighttly different namespace exposed at the very least.

And it worked. I was able to upload to s3 through the UI.

**Comment by russmac** [comment]
Delete me.

**Comment by russmac** [comment]
Alternatively use the install script which I fixed and submitted a pull request for.

https://github.com/russmac/frontend/commit/66c2440778830d0e7f55fadc6d5cdf8192522a6b
https://github.com/russmac/frontend/blob/master/documentation/guides/InstallationUbuntuApache.sh

**Comment by jmathai** [comment]
Would like to better understand the issue here. It looks like it fails at 'User::getNameFromEmail()` which shouldn't be called yet (I don't think). It *should* only be called if you have a session and you shouldn't yet in the setup unless.

Can you confirm if this error came up after you already tried to set Trovebox up unsuccessfully?

**Comment by joephein** [comment]
Yes I can confirm that if the setup fails subsequent tries with the same e-mail address will also fail. The only way is to manually delete the user entry from the mysql database or try again with a different e-mail address:

``` [Tue May 26 16:27:46.642966 2015] [:error] [pid 27686] [client x.x.x.x:60662] {severity:crit, description:"Could not initialize user for MySql due to email conflict (name@domain.com).", additional:}, referer: http://x.x.x.x/setup/3

[Tue May 26 16:27:46.643249 2015] [:error] [pid 27686] [client x.x.x.x:60662] {severity:warn, description:"Query error: SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry 'name@domain.com' for key 'PRIMARY' - INSERT INTO `user` (`id`,`password`,`extra`) VALUES (:id,:password,:extra)", additional:}, referer: http://x.x.x.x/setup/3 ```
